import = ["~/.config/alacritty/themes/xterm.toml"]

[env]
TERM = "screen-256color"

[font]
size = 13

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[shell]
args = ["-l", "-c", "tmux attach || tmux"]
program = "/usr/bin/bash"

[window]
dynamic_padding = true
decorations = "none"
startup_mode = "Maximized"
opacity = 0.8
