import = ["/home/robert-piringiu/.config/alacritty/themes/google.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 16

[font.normal]
family = "UbuntuMono Nerd Font Mono"
style = "Regular"

[shell]
args = ["-l", "-c", "tmux attach || tmux"]
program = "/usr/bin/bash"

[window]
decorations = "none"
startup_mode = "Maximized"
