import = ["~/.config/alacritty/themes/dracula.toml"]

[env]
TERM = "screen-256color"

[font]
size = 11

[font.normal]
family = "MesloLGS NF"
style = "Regular"

[shell]
args = ["-l", "-c", "tmux attach || tmux"]
program = "/usr/bin/bash"

[window]
dynamic_padding = true
# decorations = "none"
startup_mode = "Maximized"
# opacity = 0.8
