import = ["/home/robert-piringiu/.config/alacritty/themes/google.toml"]

[env]
TERM = "screen-256color"

[font]
size = 14

[font.normal]
family = "CaskaydiaCove NFM"
style = "Regular"

[shell]
args = ["-l", "-c", "tmux attach || tmux"]
program = "/usr/bin/bash"

[window]
decorations = "none"
startup_mode = "Maximized"
opacity = 0.7
