[env]
TERM = "xterm-256color"

[font]
size = 11

[font.normal]
family = "BlexMono Nerd Font Mono"
style = "Regular"

[terminal.shell]
args = ["-l", "-c", "tmux attach || tmux"]
program = "/usr/bin/zsh"

# [selection]
# save_to_clipboard = true

[window]
dynamic_padding = true
decorations = "none"
startup_mode = "Maximized"
# opacity = 0.8
padding = { x=4, y=4}

[general]
import = ["~/.config/alacritty/themes/rose-pine.toml"]
