[env]
TERM = "xterm-256color"

[font]
size = 12

[font.normal]
family = "JetBrains Mono Nerd Font"
style = "Regular"

[terminal.shell]
args = ["-l", "-c", "tmux attach || tmux"]
program = "/usr/bin/zsh"

[window]
dynamic_padding = true
decorations = "none"
startup_mode = "Maximized"
opacity = 0.6
padding = { x=10, y=4}

[general]
import = ["~/.config/alacritty/themes/dracula.toml"]
